### ISSUE TITLE
my app get crash on launch : Unable to get provider com.imagepicker.FileProvider

### ISSUE THREAD

**Issue by peyman-hakemi** [react-native-community/react-native-image-picker#1088] opened 2019-05-27 14:25 UTC
# Bug

react native image picker V0.28.1
and React Native V0.59.5
platform Android

app working fine with android 5 or 6 or 7 or 8 and 9
but when i want to launch the app in android 4.X my app get crash in start and not showing anything
## Environment info

React Native V0.59.5

Library version: 0.28.1

## Steps To Reproduce

i dont know to to reproduce this

Describe what you expected to happen:

im expecting to app launch in android 4 with no crash

this is my androidManifest
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.cheshmeh">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      android:usesCleartextTraffic="true">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    <intent-filter android:label="@string/app_name">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        
        <data android:scheme="cheshmehapp"
              android:host="PaymentFinish" />
    </intent-filter>

      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
<meta-data android:name="co.ronash.pushe.token" android:value="PUSHE_986776434423"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
                android:value="YOUR NOTIFICATION CHANNEL NAME"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                    android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION"/>

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
        
    </application>

</manifest>
`

and my dependencies

 "@react-native-community/async-storage": "^1.3.3",
    "@react-native-community/netinfo": "^2.0.7",
    "appcenter": "1.13.0",
    "appcenter-analytics": "1.13.0",
    "appcenter-crashes": "1.13.0",
    "jalaali-js": "^1.1.0",
    "lottie-react-native": "2.5.10",
    "moment": "^2.24.0",
    "native-base": "^2.12.1",
    "persian-tools": "^0.0.5",
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-animate-number": "^0.1.2",
    "react-native-code-push": "^5.6.0",
    "react-native-confirmation-code-input": "^1.0.4",
    "react-native-countdown-component": "^2.2.0",
    "react-native-dropdownalert": "^3.9.2",
    "react-native-fast-image": "^6.0.0",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-image-picker": "^0.28.1",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-modal": "^9.0.0",
    "react-native-modal-selector": "^1.0.3",
    "react-native-persian-calendar-picker": "^2.2.2",
    "react-native-pushe": "^1.6.0",
    "react-native-render-html": "^4.1.2",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-snap-carousel": "^3.7.5",
    "react-native-svg": "^9.3.6",
    "react-native-swiper": "^1.5.14",
    "react-native-timer-countdown": "^4.1.0",
    "react-native-vector-icons": "^6.4.2",
    "react-native-video": "^4.4.1",
    "react-navigation": "^3.5.1",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"

and i get a adb logcat for finding out what happenning and this is what im getr

> E/AndroidRuntime( 2718): FATAL EXCEPTION: main
> E/AndroidRuntime( 2718): java.lang.RuntimeException: Unable to get provider com.imagepicker.FileProvider: java.lang.ClassNotFoundException: com.imagepicker.FileProvider
> E/AndroidRuntime( 2718):        at android.app.ActivityThread.installProvider(ActivityThread.java:4563)
> E/AndroidRuntime( 2718):        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190)
> E/AndroidRuntime( 2718):        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132)
> E/AndroidRuntime( 2718):        at android.app.ActivityThread.access$1300(ActivityThread.java:130)
> E/AndroidRuntime( 2718):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
> E/AndroidRuntime( 2718):        at android.os.Handler.dispatchMessage(Handler.java:99)
> E/AndroidRuntime( 2718):        at android.os.Looper.loop(Looper.java:137)
> E/AndroidRuntime( 2718):        at android.app.ActivityThread.main(ActivityThread.java:4745)
> E/AndroidRuntime( 2718):        at java.lang.reflect.Method.invokeNative(Native Method)
> E/AndroidRuntime( 2718):        at java.lang.reflect.Method.invoke(Method.java:511)
> E/AndroidRuntime( 2718):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
> E/AndroidRuntime( 2718):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
> E/AndroidRuntime( 2718):        at dalvik.system.NativeStart.main(Native Method)
> E/AndroidRuntime( 2718): Caused by: java.lang.ClassNotFoundException: com.imagepicker.FileProvider
> E/AndroidRuntime( 2718):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
> E/AndroidRuntime( 2718):        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
> E/AndroidRuntime( 2718):        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
> E/AndroidRuntime( 2718):        at android.app.ActivityThread.installProvider(ActivityThread.java:4548)
> E/AndroidRuntime( 2718):        ... 12 more
> W/ActivityManager( 1389):   Force finishing activity com.cheshmeh/.MainActivity

**Comment by Nemferno** [comment] 2019-07-09 18:31
After some researching, I found a fix for this issue. From my logcat, it had displayed the following exception:

> Caused by: **java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider"** on path: DexPathList[[zip file "/data/app/-O3xaO0W09tvR-qWF1rXHwA==/base.apk"],nativeLibraryDirectories=[/data/app/lib/arm64, /data/app/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
> ...
> 07-09 13:59:33.222 32084 32084 E AndroidRuntime: **java.lang.RuntimeException: Unable to get provider com.imagepicker.FileProvider: java.lang.ClassNotFoundException: Didn't find class "com.imagepicker.FileProvider"** on path: DexPathList[[zip file "/data/app/-O3xaO0W09tvR-qWF1rXHwA==/base.apk"],nativeLibraryDirectories=[/data/app/-O3xaO0W09tvR-qWF1rXHwA==/lib/arm64, /data/app/O3xaO0W09tvR-qWF1rXHwA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
> 07-09 13:59:33.222 32084 32084 E AndroidRuntime: Caused by: **java.lang.ClassNotFoundException: Didn't find class "com.imagepicker.FileProvider"** on path: DexPathList[[zip file "/data/app/O3xaO0W09tvR-qWF1rXHwA==/base.apk"],nativeLibraryDirectories=[/data/app/-O3xaO0W09tvR-qWF1rXHwA==/lib/arm64, /data/app/-O3xaO0W09tvR-qWF1rXHwA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]

The problem is your React Native android project is not in AndroidX while react-native-image-picker is in an AndroidX environment; therefore, it is missing packages from the androidx package library. Simple fix is adding the following lines to your `./android/gradle.properties` file:

> android.useAndroidX=true
> android.enableJetifier=true

If you have any existing RN libraries that uses old android packages, your project won't build since they will be missing once you updated your project. [See here](https://developer.android.com/jetpack/androidx/migrate) for all the packages that have been refactored.

A clever tool found [here](https://stackoverflow.com/questions/56706685/react-native-error-while-generating-the-main-dex-list) deals with RN libraries that uses old android packages and brings them up to date.

> npm i --save-dev jetifier
> npx jetify
> npx react-native run-android

All checked out and it's working on my end. Hope this helps anyone and please do share if it does.

**Comment by Nemferno** [comment] 2019-07-09 18:33
The issue has been resolved 9 hours ago checking back. #1092

**Comment by h4m3d66** [comment] 2019-07-14 06:44
same issue on the latest version v1.0.1

**Comment by JB-CHAUVIN** [comment] 2019-07-23 10:43
Same issue goes for me.

**Closed** 2019-07-25 06:08 UTC

**Comment by lahed** [comment] 2019-07-25 20:48
Same issue  v1.0.1

**Comment by winseyli** [comment] 2019-08-01 10:11
same issue with 1.0.1
RN0.59.9
